"""Add image_url and is_completed to goals

Revision ID: 53638766a588
Revises: 5a4ba43d7614
Create Date: 2026-09-01 15:38:42.243002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53638766a588'
down_revision: Union[str, Sequence[str], None] = '5a4ba43d7614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('goals', sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'is_completed')
    op.drop_column('goals', 'image_url')
    # ### end Alembic commands ###
