"""Add source to transactions

Revision ID: 5a4ba43d7614
Revises: 4bdbcd5a742e
Create Date: 2026-08-31 21:15:39.627415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4ba43d7614'
down_revision: Union[str, Sequence[str], None] = '4bdbcd5a742e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('source', sa.String(), server_default='self_tax', nullable=False))
    op.create_check_constraint('transactions_source_check', 'transactions', "source IN ('self_tax', 'abandoned_purchase')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_source_check', 'transactions', type_='check')
    op.drop_column('transactions', 'source')
    # ### end Alembic commands ###
